// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHGeCiRbhO9lHJiHqNd3YlmdA7sdxoeQ',
    appId: '1:399589665504:android:8b5aa67a3402ce2ca8be85',
    messagingSenderId: '399589665504',
    projectId: 'stthi-4fb6b',
    storageBucket: 'stthi-4fb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTmvcQzNeUqrfZpdPDAF7yWTZfGXNl70',
    appId: '1:399589665504:ios:dceef4f633a449aea8be85',
    messagingSenderId: '399589665504',
    projectId: 'stthi-4fb6b',
    storageBucket: 'stthi-4fb6b.firebasestorage.app',
    iosBundleId: 'com.setthi.app.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTmvcQzNeUqrfZpdPDAF7yWTZfGXNl70',
    appId: '1:399589665504:ios:06416e0fd5d28ac2a8be85',
    messagingSenderId: '399589665504',
    projectId: 'stthi-4fb6b',
    storageBucket: 'stthi-4fb6b.firebasestorage.app',
    iosBundleId: 'com.example.setthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS5b0MbK7D0NRuS5jlilGHdO8NVkLrOM4',
    appId: '1:399589665504:web:30d64b3780d50d05a8be85',
    messagingSenderId: '399589665504',
    projectId: 'stthi-4fb6b',
    authDomain: 'stthi-4fb6b.firebaseapp.com',
    storageBucket: 'stthi-4fb6b.firebasestorage.app',
    measurementId: 'G-574X1HMHXD',
  );
}
